# Generated by Django 4.2.6 on 2023-10-14 09:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_contractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='dt_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата и время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractor',
            name='dt_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего изменения'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='to_remove',
            field=models.BooleanField(default=False, verbose_name='Помечен на удаление'),
        ),
    ]
