# Generated by Django 4.2.6 on 2023-10-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_contractor_dt_created_contractor_dt_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True, verbose_name='Пользователь')),
                ('operation', models.TextField(verbose_name='Операция')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время операции')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
                'ordering': ['-dt_created'],
            },
        ),
    ]
