# Generated by Django 4.2.6 on 2023-10-14 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_operation'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего изменения')),
                ('to_remove', models.BooleanField(default=False, verbose_name='Помечен на удаление')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='main.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар на складе',
                'verbose_name_plural': 'Товары на складе',
            },
        ),
    ]
