# Generated by Django 4.2.6 on 2023-10-14 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_storageitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего изменения')),
                ('to_remove', models.BooleanField(default=False, verbose_name='Помечен на удаление')),
                ('destination_type', models.CharField(choices=[('receipt', 'Приход'), ('expense', 'Расход')], max_length=7, verbose_name='Тип документа')),
                ('apply_flag', models.BooleanField(default=False, verbose_name='Документ проведен')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.contractor', verbose_name='Контрагент')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-dt_created'],
            },
        ),
    ]
