# Generated by Django 4.2.6 on 2023-10-14 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.document', verbose_name='Документ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар в документе',
                'verbose_name_plural': 'Товары в документе',
            },
        ),
    ]
