# Generated by Django 4.2.6 on 2023-11-11 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_product_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование компании')),
                ('address', models.TextField(blank=True, default='', null=True, verbose_name='Адрес компании')),
            ],
            options={
                'verbose_name': 'Логистическая компания',
                'verbose_name_plural': 'Логистические компании',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.company', verbose_name='Логистическая компания'),
        ),
    ]
